### ISSUE TITLE
How to finetune with my own txt dataset?

### ISSUE THREAD

**Issue by Cyberninja101** [georgesung/llm_qlora#4]
Hi, I am a bit new to Huggingface and finetuning, but how can I change the yaml config file to finetune on my custom txt dataset. For reference, this is what my txt dataset looks like: 
<img width="951" alt="Screenshot 2023-08-06 at 3 15 59 PM" src="https://github.com/georgesung/llm_qlora/assets/53117645/ff6cc6c2-c12c-4cb5-9089-e6ccba3b79ce">

Thank you so much!

**Comment by georgesung** [comment]
Looks like you want to fine-tune on raw text, in which case I'd fine tune on top of the base model. I did create `data_processor/RawTextDataProcessor.py` for this use case, but I am still tinkering with it so things might not work right away for you. The use case I was targeting was to take a list of long text files and chunk each of them before feeding them into the model for fine-tuning. In your case it looks like you have many small chunks of text already in a structured format. I
don't have your use case supported out of the box at this time. If you want, you can take a look at `RawTextDataProcessor.py` and maybe create a similar class, and you can reference the config file below that I'm using to tinker with fine-tuning on raw text files -- my particular use case was chunking a big text file and feeding the text chunks into the model for fine-tuning.

```
model_name: llama2_7b_<your model name>
base_model: TheBloke/Llama-2-7B-fp16
model_family: llama  # if unspecified will use AutoModelForCausalLM/AutoTokenizer
model_context_window: 3072 #2048 #4096  # modify the length to fit your GPU memory
data:
  type: raw_text
  text_files: # local files
    - data/your_text_file.txt
  chunk_char_len: 13000 #8700 #17000  # char length of each text chunk
  chunk_char_overlap: 300 #500  # char overlap of each text chunk
  chunk_prefix: ""
lora:
  r: 64
  lora_alpha: 16
  target_modules:  # modules for which to train lora adapters
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  lora_dropout: 0.05
  bias: none
  task_type: CAUSAL_LM
trainer:
  batch_size: 1
  gradient_accumulation_steps: 4
  warmup_steps: 70
  num_train_epochs: 30
  learning_rate: 0.0002  # 2e-4
  logging_steps: 20
trainer_output_dir: trainer_outputs/
model_output_dir: models/  # model saved in {model_output_dir}/{model_name}

# for reference, Guanaco config: https://huggingface.co/timdettmers/guanaco-33b/blob/main/adapter_config.json

```
